#!/bin/bash

function hook {

  if [ -f /etc/zfsUnlocker/zfsUnlocker.conf ]
  then
    . /etc/zfsUnlocker/zfsUnlocker.conf
  else
    echo -e "\t\t/etc/zfsUnlocker/zfsUnlocker.conf missing, skipping module."
    return 1
  fi

  if [ -n "${timeoutSeconds}" ]
  then
    if [[ "${timeoutSeconds}" =~ ^[0-9]+$ ]]
    then
      if [ ${timeoutSeconds} -lt 60 ]
      then
        echo -e "\t\t${timeoutSeconds} value too low for timeoutSeconds variable. Clamping to minimum of: 60 seconds ('60')"
        timeoutSeconds=60
      fi
      sleep ${timeoutSeconds} && reboot -f &
      echo -e "\t\tReboot timeout started lasting ${timeoutSeconds} seconds..."
    else
      echo -e "\t\ttimeoutSeconds not formatted as a number. Skipping timeout reboot module."
    fi
  else
    echo -e "\t\ttimeoutSeconds not defined. Skipping timeout reboot module."
  fi

}

function cleanup {
  pkill sleep
  # We cannot access ${ourBondInterfaces} here set by the main hook.
  # Lazily remove all numbered bond interfaces (This may not be a good idea for certain configurations)
  for bondInterface in $(find /sys/class/net -mindepth 1 -maxdepth 1 -name bond[0-9] -printf '%f\n')
  do
    bondInterfaceBasename="$(basename ${bondInterface})"
    echo -e "\t\tRemoving bond link: ${bondInterfaceBasename}"
    ip link del ${bondInterfaceBasename}
  done
}

$1

