#!/bin/bash

function hook {

  if [ -f /etc/zfsUnlocker/zfsUnlocker.conf ]
  then
    . /etc/zfsUnlocker/zfsUnlocker.conf
  else
    echo "/etc/zfsUnlocker/zfsUnlocker.conf missing, skipping module."
    return 1
  fi

  if [ -z "$wirelessNetworks" ]
  then
    echo -e "\t\tNo SSID set in zfsUnlocker.conf, skipping module."
    return 1
  else
    echo -e "\t\tTrying to join a wireless network..."

    [ ! -h /dev/fd ] && ln -s /proc/self/fd /dev/fd >/dev/null 2>&1

    interfaces="$(find /sys/class/net -mindepth 1)"

    for interface in $interfaces # Look for wireless interfaces
    do
      if [ -d $interface/wireless ]
      then
	interfaceShort="$(basename $interface)"
        echo -e "\t\tDetected: $interfaceShort"
	wirelessInterfaces+="$interfaceShort "
      fi
    done 
  fi

    if [ -z "$wirelessInterfaces" ] ; then echo -e "\t\tNo wireless interfaces seen. Did the drivers add correctly?" ; exit 1 ; fi
    for wirelessInterface in $wirelessInterfaces ; do interfaceArgs+="-i $wirelessInterface " ; done

    # Build configuration
    for network in ${!wirelessNetworks[@]}
    do
      SSID="$( cut -f1 -d':' <<< ${wirelessNetworks[${network}]})"
       PSK="$( cut -f2 -d':' <<< ${wirelessNetworks[${network}]})"
      wpa_supplicant_configuration+="$(echo -e "\nnetwork={\n  ssid=\"${SSID}\"\n  psk=${PSK}\n}")"
    done
    echo "${wpa_supplicant_configuration}"
    echo -ne '\t\t'; wpa_supplicant -B ${interfaceArgs} -c <(echo "${wpa_supplicant_configuration}") 
}

function cleanup {
  killall -q wpa_supplicant
}

$1
