#!/bin/bash

function hook {

  if [ -f /etc/zfsUnlocker/zfsUnlocker.conf ]
  then
    . /etc/zfsUnlocker/zfsUnlocker.conf
  else
    echo "/etc/zfsUnlocker/zfsUnlocker.conf missing, skipping vault module."
    return 1
  fi

  if [ -z "$SSID" ]
  then
    echo -e "\t\tNo SSID set in zfsUnlocker.conf, skipping module."
  else
    echo -e "\t\tTrying to join a wireless network..."

    [ ! -h /dev/fd ] && ln -s /proc/self/fd /dev/fd >/dev/null 2>&1

    interfaces="$(find /sys/class/net -mindepth 1)"

    for interface in $interfaces # Look for wireless interfaces
    do
      if [ -d $interface/wireless ]
      then
	interfaceShort="$(basename $interface)"
        echo -e "\t\tDetected: $interfaceShort"
	wirelessInterfaces+="$interfaceShort "
      fi
    done 
  fi

    if [ -z "$wirelessInterfaces" ] ; then echo -e "\t\tNo wireless interfaces seen. Did the drivers add correctly?" ; exit 1 ; fi
    for wirelessInterface in $wirelessInterfaces ; do interfaceArgs+="-i $wirelessInterface " ; done

    echo -ne '\t\t'; wpa_supplicant -B ${interfaceArgs} -c <(echo -e "network={\n  ssid=\"${SSID}\"\n  psk=${PSK}\n}") 
}

function cleanup {
  killall wpa_supplicant
}

$1
