#!/bin/bash

function hook {

  if [ -f /etc/zfsUnlocker/zfsUnlocker.conf ]
  then
    . /etc/zfsUnlocker/zfsUnlocker.conf
  else
    echo "\t\t/etc/zfsUnlocker/zfsUnlocker.conf missing, skipping module."
    return 1
  fi

  if [ -z "${PART_UUID}" ] || [ -z "${PASSPHRASE_FILE_PATH}" ]
  then
    echo -e "\t\tPART_UUID or PASSPHRASE_FILE_PATH not set. Skipping module."
    return 1
  fi

  mkdir -p /keyFileMount
  set -o pipefail
  if ! mount /dev/disk/by-partuuid/${PART_UUID} /keyFileMount 2>&1 | sed -E -e 's/^/\t\t/g'
  then
    echo -e "\t\tFailed to mount the desired partition UUID."
    return 1
  fi
  set +o pipefail

  if ! [ -f "/keyFileMount/${PASSPHRASE_FILE_PATH}" ]
  then
    echo -e "\t\tKeyfile ${PASSPHRASE_FILE_PATH} not found on the mounted filesystem."
    return 1
  fi

  # Try all passphrase lines in the text file
  while read line
  do
    yes "${line}" | zfs load-key -a 2>&1 | sed -E -e 's/^/\t\t/g'
  done <<< "$(cat "/keyFileMount/${PASSPHRASE_FILE_PATH}")"
}

function cleanup {
  if grep -qs keyFileMount /proc/mounts
  then
    umount    /keyFileMount
    rmdir -p  /keyFileMount
  fi
}

${1}
