#!/bin/bash

function hook {
  echo -e "\t\tGetting an IP..."
  if dhclient -1 >/dev/null 2>&1
  then
    if [ -f '/var/lib/dhclient/dhclient.leases' ]
    then
      myAddress="$(grep -m1 -o 'fixed-address.*' /var/lib/dhclient/dhclient.leases |grep -Eo '([0-9]+|\.)+')"
      [ -n "$myAddress" ] && echo -e "\t\tGot address $myAddress"
    fi
  else
    echo "\t\tCouldn't get an IP, manual unlock may be required."
  fi

}

function cleanup {
    # Release the lease
  dhclient -r >/dev/null 2>&1
}

$1
